### ISSUE TITLE
Memory caching not caching

### ISSUE THREAD

**Issue by thenitai** [boblauer/cachegoose#15]
Hi,

Love this module. Works perfectly with Redis. However, I've found that it doesn't when using memory only. Example:

```
.find({}).cache(0, 'myawesomekey').exec()
```
Now. if I change any records and execute the above query again the changed records do show up. I was expecting that the "old" (cached) records show. Am I missing something?

Thanks.

**Comment by boblauer** [comment]
I'm guessing what is happening is you're actually updating the in-memory cached results.  So in other words, if you do:

```js
find(().cache(0, 'myawesomekey').exec().then(records => {
  records[0].title = 'new value';
});
```

you're updating the object that's in the cache, so the next time you run your query, you're getting back that same object.

This is why it works with Redis, because you're not updating Redis directly when you modify the results of the query.

If you want to avoid this behavior, you'll need to make copies of the query results before updating them.

Closing this for now, but feel free to re-open if you think i'm misunderstanding the issue.

**Comment by thenitai** [comment]
Sorry just saw your reply...

Ok, so bear with me (coming from other cache technologies merely with Java), as I understand, the cache is being updated according to the query, right?

So, if I have a collection and need results PER USER, I would have to put the userid in the cache key, i.e. "mykey_userid_108". 

Now, what is the best approach for a cache key that queries again on the SAME collection, but a different query? For example:

```
db.product.find({ status : 'A', user_id:'108').cache(0, 'mykey_userid_108')
```
and
```
db.product.find({ status : 'B', user_id:'108').cache(0, 'mykey_userid_108')
```

In this case, will the second query overwrite the results in the first one or will it behave that it will store queries within the cachekey? I hope you understand what I mean.

Thank you.

**Comment by boblauer** [comment]
In that scenario, you have 2 options:

1. Don't specify the cache key at all, and let mongoose generate it internally.  Because the query conditions are different (`status: 'A' vs status: 'B'`), it will generate different keys for those queries, and it won't overwrite the results.

2. If you do need to specify the cache key yourself (this is useful if you want to later clear the cache manually), you could do something alone the lines of:

```js
var query = { status: 'A', user_id: '108' };
db.product.find(query).cache(0, JSON.stringify(query));
```

and

```js
var query = { status: 'B', user_id: '108' };
db.product.find(query).cache(0, JSON.stringify(query));
```

That way the cache key will be unique for each query.  (This is essentially what cachegoose does internally to generate a cache key, although it's slightly more complicated).

I hope that helps.

**Comment by thenitai** [comment]
Thank you for your answer. This is very helpful. 

I rather have control over the cache and also like to cache as long as possible. Hence, I opt for the cache key.
